export const UPDATE_QUESTIONNARE = "UPDATE_QUESTIONNARE"
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"
export const UPDATE_APP_DATA = "UPDATE_APP_DATA"
export const UPDATE_APP_NAME = "UPDATE_APP_NAME"